[package]
name = "jistR"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jistR"
path = "src/main.rs"

[dependencies]
crossterm = "0.26"
rand = "0.8"
lazy_static = "1.4"
ansi_term = "0.12"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "1.0"
